services:

  postgres:
    image: postgres:17

    container_name: sc_postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

    volumes:
      - postgres_data:/var/lib/postgresql/data


  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: sc_backend

    env_file:
      - .env

    depends_on:
      - postgres

    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: sc_frontend

    restart: unless-stopped

    depends_on:
      - backend


  nginx:
    image: nginx:alpine

    container_name: sc_nginx

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro  

    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
