"""empty message

Revision ID: 1f7e3e2b2d71
Revises: 
Create Date: 2026-08-11 10:48:09.893815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f7e3e2b2d71'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=14), nullable=False),
    sa.Column('client_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('recovery_code',
    sa.Column('code_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('recovery_code', sa.String(), nullable=False),
    sa.Column('code_created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('code_expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_table('refresh_token',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_table('service_appointments',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_username', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_types', sa.String(), nullable=False),
    sa.Column('custom_event', sa.String(length=150), nullable=True),
    sa.Column('service_types', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('custom_service', sa.String(length=300), nullable=True),
    sa.Column('optional_kitchens', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('estimated_event_date', sa.Date(), nullable=False),
    sa.Column('estimated_guests_quantity', sa.Integer(), nullable=True),
    sa.Column('estimated_budget', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('event_address', sa.String(length=300), nullable=False),
    sa.Column('optional_observations', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_appointment')
    op.drop_table('refresh_token')
    op.drop_table('recovery_code')
    op.drop_table('client')
    # ### end Alembic commands ###
