"""Client and Complete Service Pack tables

Revision ID: c42a66f33f5b
Revises: 
Create Date: 2026-06-28 14:30:30.528074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c42a66f33f5b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=14), nullable=False),
    sa.Column('client_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('complete_service_pack',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('complete_name', sa.String(), nullable=False),
    sa.Column('cep_number', sa.String(length=8), nullable=True),
    sa.Column('state_name', sa.String(length=30), nullable=True),
    sa.Column('city_name', sa.String(length=30), nullable=True),
    sa.Column('thoroughfare', sa.String(), nullable=True),
    sa.Column('thoroughfare_number', sa.String(length=10), nullable=True),
    sa.Column('extra_locale_info', sa.String(length=50), nullable=True),
    sa.Column('guests_number', sa.Integer(), nullable=True),
    sa.Column('inicial_budget', sa.Float(), nullable=True),
    sa.Column('client_owner_id', sa.Integer(), nullable=False),
    sa.Column('owner_phone_number', sa.String(length=14), nullable=False),
    sa.ForeignKeyConstraint(['client_owner_id'], ['client.client_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_phone_number'], ['client.phone_number'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complete_service_pack')
    op.drop_table('client')
    # ### end Alembic commands ###
